name: generate animation

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          
        # Options
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: >-
            scss, css, php, roff, xslt
          plugin_languages_details: percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_languages_skipped: pjnp5
          plugin_languages_threshold: 1%
          
